version: "2"
services:
  app:
    container_name: app
    image: restapi-demo
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: sumglobal/rpi-mongodb
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
